[package]
name = "dbost-migration"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
uuid = "1.4.1"
tokio = { version = "1.31.0", features = ["macros", "rt-multi-thread"] }
sea-orm-migration = { version = "0.12.1", default-features = false, features = [
	"cli",
	"sqlx-postgres",
	"runtime-tokio-rustls",
	"with-uuid",
	"with-time",
] }
