name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run lint & tests
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - name: Install mold
        uses: rui314/setup-mold@v1
        with:
          mold-version: 2.1.0
          make-default: false

      - name: Add symlink for mold
        run: ln -s /usr/local/bin/mold /usr/bin/mold

      - name: Lint
        run: cargo clippy --workspace -- -D warnings

      - name: Run tests
        run: cargo test --workspace --all-features

  build:
    runs-on: ubuntu-latest
    name: Build images
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v3
        env:
          GIT_SHA: ${{ github.sha }}
          version: ${{ github.sha }}
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          files: docker-bake.hcl

      # - name: Tag images
      #   shell: bash
      #   run: |
      #     docker buildx imagetools

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to AWS
    needs:
      - build
      - test

    if: github.ref == 'refs/heads/main'

    concurrency:
      group: aws

    environment:
      name: aws
      url: https://dbost.tv

    steps:
      - name: Deploy to AWS
        shell: bash
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }} \
            -e RUST_BACKTRACE=full \
            ghcr.io/alxandr/dbost/deployer:${{ github.sha }}
